CREATE TABLE IF NOT EXISTS shops (
  id SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  owner_user_id SMALLINT NOT NULL,
  name VARCHAR(160) NOT NULL,
  slug VARCHAR(180) NOT NULL UNIQUE,
  address_line1 VARCHAR(255) NOT NULL,
  city VARCHAR(120) NOT NULL,
  country VARCHAR(120) NOT NULL,
  phone VARCHAR(30),
  email VARCHAR(255),
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_shops_owner_user_id ON shops(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_shops_city ON shops(city);
